# Generated by Django 5.2.5 on 2025-08-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[('HORROR', 'Terror'), ('COMEDY', 'Comedia'), ('FICCTION', 'Ficção'), ('DOCUMENTARY', 'Documentario'), ('ACTION', 'Ação')], max_length=100)),
                ('published_date', models.DateField()),
                ('photo', models.TextField()),
                ('classification', models.IntegerField()),
            ],
        ),
    ]
